name: Maven Workflow

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Create target directory manually
        run: |
          mkdir -p target
      - name: Build with Maven
        run: mvn clean compile  

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build 
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn test  

  surefire-report:
    name: Generate Surefire Report
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - uses: actions/checkout@v4
      - name: Generate Surefire Report (HTML)
        run: mvn surefire-report:report  
      - name: Upload Surefire Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/ 

  jacoco-coverage:
    name: Generate and Upload JaCoCo Coverage Report
    runs-on: ubuntu-latest
    needs: surefire-report  
    steps:
      - uses: actions/checkout@v4
      - name: Run JaCoCo Report
        run: mvn jacoco:report 
      - name: Upload JaCoCo Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: 'target/site/jacoco/jacoco.xml'  
          fail_ci_if_error: true

  update-readme:
    name: Update README with Test Results and Coverage
    runs-on: ubuntu-latest
    needs: jacoco-coverage  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Test Results
        id: get_test_results
        run: |
          FAILURE_COUNT=$(find target/surefire-reports/ -type f -name "*.txt" -exec grep -c 'FAILURE' {} \; | awk '{s+=$1} END {print s}')
          ERROR_COUNT=$(find target/surefire-reports/ -type f -name "*.txt" -exec grep -c 'ERROR' {} \; | awk '{s+=$1} END {print s}')
          TOTAL_TESTS=$(find target/surefire-reports/ -type f -name "*.txt" -exec grep -o 'Tests run: [0-9]*' {} \; | awk '{sum += $3} END {print sum}')
          
          echo "FAILURE_COUNT=$FAILURE_COUNT" >> $GITHUB_ENV
          echo "ERROR_COUNT=$ERROR_COUNT" >> $GITHUB_ENV
          echo "TOTAL_TESTS=$TOTAL_TESTS" >> $GITHUB_ENV

      - name: Update README.md with Test and Coverage Results
        run: |
          echo "## Testes Resultados" > README.md
          echo "Total Tests Run: $TOTAL_TESTS" >> README.md
          echo "Falhas: $FAILURE_COUNT" >> README.md
          echo "Erros: $ERROR_COUNT" >> README.md
          echo "Veja o reporte completo em target/surefire-reports/" >> README.md
          
          echo "## JaCoCo Cobertura" >> README.md
          echo "Veja JaCoCo reporte completo em target/site/jacoco/index.html" >> README.md

      - name: Commit and push README update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with test and coverage results"
          git push
